[project]
name = "qpay-client"
version = "0.3.2"
description = "QPay Integration made easy (async & sync, typed schemas, auto token refresh)"
readme = "README.md"
authors = [{ name = "Amraa1", email = "amarsanaaganbaatar0409@gmail.com" }]
requires-python = ">=3.9"
dependencies = ["httpx>=0.28.1", "pydantic>=2.10.0"]
license = { file = "LICENSE.txt" }
keywords = [
  "qpay",
  "payment",
  "qpay v2",
  "mongolian payment",
  "mongolia",
  "httpx",
  "pydantic",
  "asyncio",
]

classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://pypi.org/project/qpay-client/"
Documentation = "https://pypi.org/project/qpay-client/"
Source = "https://github.com/Amraa1/qpay_client"
Issues = "https://github.com/Amraa1/qpay_client/issues"


[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "pytest>=8",
  "pytest-asyncio>=0.23",
  "anyio>=4",
  "respx>=0.21",
  "ruff>=0.13.0",
  "mypy>=1.11",
  "types-requests",
  "pytest-cov>=7.0.0",
]
